name: Release

on:
  push:
    tags:
      - "*.*.*"

defaults:
  run:
    working-directory: c182rg-improvement-project

permissions:
  id-token: write
  contents: write

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: set up node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: build code
        run: npm run build
      - name: rename build folder
        run: Rename-Item -Path build -NewName c182rg-improvement-project
      - name: package code
        run: Compress-Archive -Path c182rg-improvement-project -DestinationPath c182rg-improvement-project.zip
      - name: ls
        run: Get-ChildItem
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: |
            ./c182rg-improvement-project.zip